[
  {
    student_id: 1,
    first_name: "Alfonso",
    last_name: "Seckington",
    age: 18,
    email: "aseckington0@github.io",
    phone_number: "570-885-6734",
    address: "7748 Division Trail",
    course: "Engineering",
  },
  {
    student_id: 2,
    first_name: "Northrop",
    last_name: "Tallon",
    age: 22,
    email: "ntallon1@multiply.com",
    phone_number: "807-113-5068",
    address: "249 Loomis Terrace",
    course: "Science",
  },
  {
    student_id: 3,
    first_name: "Jerald",
    last_name: "Kobieriecki",
    age: 18,
    email: "jkobieriecki2@paginegialle.it",
    phone_number: "430-697-8672",
    address: "757 Elka Hill",
    course: "Medicine",
  },
  {
    student_id: 4,
    first_name: "Kingston",
    last_name: "Michael",
    age: 23,
    email: "kmichael3@walmart.com",
    phone_number: "576-169-7099",
    address: "9422 Macpherson Drive",
    course: "Science",
  },
  {
    student_id: 4,
    first_name: "Kingston",
    last_name: "Michael",
    age: 23,
    email: "kmichael3@walmart.com",
    phone_number: "576-169-7099",
    address: "9422 Macpherson Drive",
    course: "Science",
  },
  {
    student_id: 6,
    first_name: "Chadd",
    last_name: "Brumby",
    age: 25,
    email: "cbrumby5@myspace.com",
    phone_number: "508-568-7858",
    address: "2909 Sullivan Parkway",
    course: "Engineering",
  },
  {
    student_id: 7,
    first_name: "Martyn",
    last_name: "Cowpland",
    age: 22,
    email: "mcowpland6@npr.org",
    phone_number: "447-355-4898",
    address: "8 South Lane",
    course: "Arts",
  },
  {
    student_id: 8,
    first_name: "Salmon",
    last_name: "Corderoy",
    age: 23,
    email: "scorderoy7@delicious.com",
    phone_number: "680-287-2150",
    address: "7184 Armistice Crossing",
    course: "Medicine",
  },
  {
    student_id: 9,
    first_name: "Morty",
    last_name: "Flood",
    age: 20,
    email: "mflood8@cyberchimps.com",
    phone_number: "923-511-1209",
    address: "05 Rieder Alley",
    course: "Science",
  },
  {
    student_id: 10,
    first_name: "Trace",
    last_name: "Frandsen",
    age: 20,
    email: "tfrandsen9@sfgate.com",
    phone_number: "108-475-4427",
    address: "9 Mccormick Parkway",
    course: "Arts",
  },
  {
    student_id: 11,
    first_name: "Duffy",
    last_name: "Kenzie",
    age: 23,
    email: "dkenziea@bbc.co.uk",
    phone_number: "661-862-9041",
    address: "23342 Golf Course Street",
    course: "Engineering",
  },
  {
    student_id: 12,
    first_name: "Eduard",
    last_name: "Zini",
    age: 25,
    email: "ezinib@bluehost.com",
    phone_number: "352-222-1401",
    address: "595 Boyd Court",
    course: "Arts",
  },
  {
    student_id: 13,
    first_name: "Conrade",
    last_name: "Filippozzi",
    age: 23,
    email: "cfilippozzic@behance.net",
    phone_number: "141-725-5507",
    address: "453 Mayfield Trail",
    course: "Arts",
  },
  {
    student_id: 14,
    first_name: "Vlad",
    last_name: "Delahunty",
    age: 25,
    email: "vdelahuntyd@hc360.com",
    phone_number: "671-742-7263",
    address: "877 Forest Pass",
    course: "Science",
  },
  {
    student_id: 15,
    first_name: "Virge",
    last_name: "Moralas",
    age: 20,
    email: "vmoralase@nbcnews.com",
    phone_number: "784-792-6058",
    address: "465 Farwell Plaza",
    course: "Medicine",
  },
  {
    student_id: 16,
    first_name: "Diarmid",
    last_name: "Abramsky",
    age: 24,
    email: "dabramskyf@clickbank.net",
    phone_number: "571-210-2118",
    address: "9 Division Plaza",
    course: "Science",
  },
  {
    student_id: 17,
    first_name: "Christie",
    last_name: "Mortimer",
    age: 25,
    email: "cmortimerg@harvard.edu",
    phone_number: "467-425-3721",
    address: "0477 Manufacturers Park",
    course: "Medicine",
  },
  {
    student_id: 18,
    first_name: "Russ",
    last_name: "Herkess",
    age: 18,
    email: "rherkessh@mozilla.com",
    phone_number: "394-759-4733",
    address: "08218 Pierstorff Lane",
    course: "Engineering",
  },
  {
    student_id: 19,
    first_name: "Wake",
    last_name: "Olivetta",
    age: 22,
    email: "wolivettai@independent.co.uk",
    phone_number: "412-884-6392",
    address: "69957 Talmadge Hill",
    course: "Medicine",
  },
  {
    student_id: 20,
    first_name: "Courtney",
    last_name: "Arendt",
    age: 24,
    email: "carendtj@wired.com",
    phone_number: "889-776-8595",
    address: "76 Myrtle Way",
    course: "Arts",
  },
  {
    student_id: 21,
    first_name: "Darrick",
    last_name: "Wroughton",
    age: 19,
    email: "dwroughtonk@about.com",
    phone_number: "368-832-8246",
    address: "90398 Northridge Place",
    course: "Science",
  },
  {
    student_id: 22,
    first_name: "Giordano",
    last_name: "Pantling",
    age: 23,
    email: "gpantlingl@ucla.edu",
    phone_number: "523-554-8889",
    address: "4 Heath Avenue",
    course: "Engineering",
  },
  {
    student_id: 23,
    first_name: "Amerigo",
    last_name: "Kippie",
    age: 22,
    email: "akippiem@walmart.com",
    phone_number: "412-413-8438",
    address: "263 Quincy Court",
    course: "Engineering",
  },
  {
    student_id: 24,
    first_name: "Wilbur",
    last_name: "Dmitrichenko",
    age: 25,
    email: "wdmitrichenkon@patch.com",
    phone_number: "447-539-6597",
    address: "028 Hovde Place",
    course: "Medicine",
  },
  {
    student_id: 25,
    first_name: "Chas",
    last_name: "Harmon",
    age: 23,
    email: "charmono@apache.org",
    phone_number: "760-546-3311",
    address: "37812 Sutteridge Parkway",
    course: "Medicine",
  },
  {
    student_id: 26,
    first_name: "Tristan",
    last_name: "Rozenbaum",
    age: 25,
    email: "trozenbaump@berkeley.edu",
    phone_number: "806-158-1681",
    address: "1815 Forest Run Road",
    course: "Science",
  },
  {
    student_id: 27,
    first_name: "Kippy",
    last_name: "Soames",
    age: 25,
    email: "ksoamesq@google.com",
    phone_number: "902-687-9936",
    address: "742 Messerschmidt Terrace",
    course: "Engineering",
  },
  {
    student_id: 28,
    first_name: "Evelin",
    last_name: "Portugal",
    age: 18,
    email: "eportugalr@soundcloud.com",
    phone_number: "976-500-8946",
    address: "8386 Eliot Hill",
    course: "Science",
  },
  {
    student_id: 29,
    first_name: "Milt",
    last_name: "Tear",
    age: 23,
    email: "mtears@businessinsider.com",
    phone_number: "103-305-9230",
    address: "24066 Clemons Terrace",
    course: "Medicine",
  },
  {
    student_id: 30,
    first_name: "Dav",
    last_name: "Symons",
    age: 24,
    email: "dsymonst@nasa.gov",
    phone_number: "606-333-1432",
    address: "540 Cascade Way",
    course: "Arts",
  },
  {
    student_id: 31,
    first_name: "Sergent",
    last_name: "MacTrustam",
    age: 20,
    email: "smactrustamu@diigo.com",
    phone_number: "203-573-0048",
    address: "1755 Debra Drive",
    course: "Engineering",
  },
  {
    student_id: 32,
    first_name: "Zachary",
    last_name: "Hinckley",
    age: 21,
    email: "zhinckleyv@wikimedia.org",
    phone_number: "382-480-8281",
    address: "2 Dayton Parkway",
    course: "Medicine",
  },
  {
    student_id: 33,
    first_name: "Hagan",
    last_name: "Callam",
    age: 18,
    email: "hcallamw@sun.com",
    phone_number: "212-857-2563",
    address: "93650 Ridgeview Terrace",
    course: "Engineering",
  },
  {
    student_id: 34,
    first_name: "Ruby",
    last_name: "Arkow",
    age: 18,
    email: "rarkowx@state.gov",
    phone_number: "466-186-3932",
    address: "349 Bellgrove Point",
    course: "Arts",
  },
  {
    student_id: 35,
    first_name: "Tiebout",
    last_name: "Hadaway",
    age: 23,
    email: "thadawayy@zdnet.com",
    phone_number: "469-934-4581",
    address: "48645 Nobel Parkway",
    course: "Medicine",
  },
  {
    student_id: 36,
    first_name: "Barthel",
    last_name: "Henkmann",
    age: 20,
    email: "bhenkmannz@skype.com",
    phone_number: "499-777-5576",
    address: "545 Waywood Way",
    course: "Arts",
  },
  {
    student_id: 37,
    first_name: "Alessandro",
    last_name: "Baford",
    age: 24,
    email: "abaford10@senate.gov",
    phone_number: "513-398-7328",
    address: "2 Express Center",
    course: "Science",
  },
  {
    student_id: 38,
    first_name: "Giuseppe",
    last_name: "Pedroni",
    age: 24,
    email: "gpedroni11@disqus.com",
    phone_number: "611-356-6865",
    address: "78 Londonderry Point",
    course: "Science",
  },
  {
    student_id: 39,
    first_name: "Gaylor",
    last_name: "Ettels",
    age: 24,
    email: "gettels12@newsvine.com",
    phone_number: "830-594-0418",
    address: "970 Banding Parkway",
    course: "Medicine",
  },
  {
    student_id: 40,
    first_name: "Sloane",
    last_name: "Thurstan",
    age: 20,
    email: "sthurstan13@msn.com",
    phone_number: "172-607-6286",
    address: "2 Buell Circle",
    course: "Engineering",
  },
  {
    student_id: 41,
    first_name: "Rurik",
    last_name: "Domegan",
    age: 20,
    email: "rdomegan14@china.com.cn",
    phone_number: "300-504-1174",
    address: "0947 Coolidge Trail",
    course: "Medicine",
  },
  {
    student_id: 42,
    first_name: "Benson",
    last_name: "Newens",
    age: 21,
    email: "bnewens15@usda.gov",
    phone_number: "411-997-9760",
    address: "7262 Sutherland Junction",
    course: "Arts",
  },
  {
    student_id: 43,
    first_name: "Kilian",
    last_name: "Witherow",
    age: 23,
    email: "kwitherow16@dell.com",
    phone_number: "806-966-9512",
    address: "38112 Cottonwood Circle",
    course: "Medicine",
  },
  {
    student_id: 44,
    first_name: "Cyrille",
    last_name: "Baden",
    age: 25,
    email: "cbaden17@microsoft.com",
    phone_number: "902-467-8619",
    address: "82019 Haas Alley",
    course: "Medicine",
  },
  {
    student_id: 45,
    first_name: "Gorden",
    last_name: "Barszczewski",
    age: 18,
    email: "gbarszczewski18@zimbio.com",
    phone_number: "825-405-9245",
    address: "2 Tennyson Pass",
    course: "Arts",
  },
  {
    student_id: 46,
    first_name: "Drew",
    last_name: "Sanger",
    age: 20,
    email: "dsanger19@godaddy.com",
    phone_number: "342-254-6869",
    address: "436 Russell Point",
    course: "Arts",
  },
  {
    student_id: 47,
    first_name: "Abramo",
    last_name: "Dobie",
    age: 24,
    email: "adobie1a@archive.org",
    phone_number: "279-610-9967",
    address: "94 Carpenter Trail",
    course: "Engineering",
  },
  {
    student_id: 48,
    first_name: "Laurence",
    last_name: "Webborn",
    age: 18,
    email: "lwebborn1b@cargocollective.com",
    phone_number: "893-687-4700",
    address: "44931 Tony Parkway",
    course: "Medicine",
  },
  {
    student_id: 49,
    first_name: "Morley",
    last_name: "Westell",
    age: 24,
    email: "mwestell1c@goodreads.com",
    phone_number: "179-677-0559",
    address: "71 Haas Parkway",
    course: "Medicine",
  },
  {
    student_id: 50,
    first_name: "Derward",
    last_name: "Rubinsaft",
    age: 23,
    email: "drubinsaft1d@mozilla.com",
    phone_number: "219-288-3672",
    address: "1907 Jay Court",
    course: "Engineering",
  },
];
